<template>
    <div>
      <ul>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
          <li>我爱你</li>
      </ul>
    </div>
</template>
<script>
export default {
    
}
</script>
<style scoped>
    ul {
        height: 200px;
        background-color: aquamarine;
        max-height: 200px;
        overflow-y: scroll;
    }
</style>